"""add password column to user table

Revision ID: 99d62d279654
Revises: 
Create Date: 2025-04-22 15:55:52.217785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d62d279654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('org', sa.Column('bank_password', sa.String(length=100), nullable=True))
    op.add_column('org', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('org', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('org', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'verification_code_expires')
    op.drop_column('user', 'verification_code')
    op.drop_column('user', 'is_convener')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('is_convener', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('verification_code', sa.VARCHAR(length=6), nullable=True))
    op.add_column('user', sa.Column('verification_code_expires', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'password')
    op.alter_column('org', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('org', 'updated_at')
    op.drop_column('org', 'created_at')
    op.drop_column('org', 'bank_password')
    op.drop_column('org', 'bank_name')
    # ### end Alembic commands ###
